[package]
name = "icinga_passive_checks"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
toml = "0.8.19"
