name: Make a Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Release notes for ${{ github.ref_name }}
          draft: true

  build_ubuntu20_04:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    needs: prepare
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: cargo build --release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./target/release/icinga_passive_checks
          asset_name: icinga_passive_checks.x86_64-ubuntu20.04
          asset_content_type: application/octet-stream

  build_ubuntu22_04:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: cargo build --release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./target/release/icinga_passive_checks
          asset_name: icinga_passive_checks.x86_64-ubuntu22.04
          asset_content_type: application/octet-stream

  build_ubuntu24_04:
    name: Build on Ubuntu 24.04
    runs-on: ubuntu-24.04
    needs: prepare
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        run: cargo build --release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./target/release/icinga_passive_checks
          asset_name: icinga_passive_checks.x86_64-ubuntu24.04
          asset_content_type: application/octet-stream
